package parser;

import utils.ASTNodeVisitor;
/* Generated By:JJTree: Do not edit this line. AST_new.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class AST_new extends SimpleNode {
  public String type;
  public String info;

  public AST_new(int id) {
    super(id);
  }

  public AST_new(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "new " + type + " " + info;
  }

  public String getType() {

    if (type.equals("array")) {
      return type;
    } else {
      return info;
    }
  }

  @Override
  public String accept(ASTNodeVisitor visitor) {
    return visitor.visit(this);
  }
}
/*
 * JavaCC - OriginalChecksum=71f95ffa1708d3507896129b9ea23e12 (do not edit this
 * line)
 */
