package parser;

import utils.ASTNodeVisitor;
/* Generated By:JJTree: Do not edit this line. ASTand.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTand extends SimpleNode {

  public ASTand(int id) {
    super(id);
  }

  public ASTand(jmm p, int id) {
    super(p, id);
  }

  public String getType() {
    return "bool";
  }

  @Override
  public String accept(ASTNodeVisitor visitor) {
    return visitor.visit(this);
  }

}
/*
 * JavaCC - OriginalChecksum=f0e373d6ade899c6fe25fd68511409dc (do not edit this
 * line)
 */
