package parser;

import utils.ASTNodeVisitor;
import semanticAnalysis.*;
import symbolTable.STEntry;
/* Generated By:JJTree: Do not edit this line. ASTid.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTid extends SimpleNode {
  public String info;

  public ASTid(int id) {
    super(id);
  }

  public ASTid(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "id " + info;
  }

  public String getType() {
    // Check if it is in the symbol table of simpleNode
    
    STEntry entry = checkSymbolTable(info);

    if(entry != null && entry.type.equals("int[]") && children != null)
      return "int";
      
    return (entry == null) ? "Error" : entry.type;
  }

  @Override
  public String accept(ASTNodeVisitor visitor) {
    return visitor.visit(this);
  }

  public void acceptSemanticAnalysis(SemanticAnalyzer semanticAnalyzer) {
    semanticAnalyzer.visit(this);

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode) children[i];
        if (n != null) {
          n.acceptSemanticAnalysis(semanticAnalyzer);
        }
      }
    }
  }
}
/*
 * JavaCC - OriginalChecksum=26eb977e90f51861269bce1db317103c (do not edit this
 * line)
 */
