package parser;

import utils.ASTNodeVisitor;
import semanticAnalysis.*;
/* Generated By:JJTree: Do not edit this line. ASTliteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTliteral extends SimpleNode {
  public String info;

  public ASTliteral(int id) {
    super(id);
  }

  public ASTliteral(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "literal " + info;
  }

  public String getType() {
    return "int";
  }

  @Override
  public String accept(ASTNodeVisitor visitor) {
    return visitor.visit(this);
  }

  public void acceptSemanticAnalysis(SemanticAnalyzer semanticAnalyzer) {
    semanticAnalyzer.visit(this);

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode) children[i];
        if (n != null) {
          n.acceptSemanticAnalysis(semanticAnalyzer);
        }
      }
    }
  }
}
/*
 * JavaCC - OriginalChecksum=570004d639550726751648828304833a (do not edit this
 * line)
 */
