package parser;

import utils.ASTNodeVisitor;
import semanticAnalysis.*;
/* Generated By:JJTree: Do not edit this line. ASTnot.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTnot extends SimpleNode {

  public ASTnot(int id) {
    super(id);
  }

  public ASTnot(jmm p, int id) {
    super(p, id);
  }

  public String getType() {
    return "bool";
  }

  @Override
  public String accept(ASTNodeVisitor visitor) {
    return visitor.visit(this);
  }

  public void acceptSemanticAnalysis(SemanticAnalyzer semanticAnalyzer) {
    semanticAnalyzer.visit(this);

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode) children[i];
        if (n != null) {
          n.acceptSemanticAnalysis(semanticAnalyzer);
        }
      }
    }
  }
}
/*
 * JavaCC - OriginalChecksum=fb8d63593e6952b5ae4d23414e6729e2 (do not edit this
 * line)
 */
