/* Generated By:JJTree: Do not edit this line. AST_this.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AST_this extends SimpleNode {
  public AST_this(int id) {
    super(id);
  }

  public AST_this(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fba6d607a89996b150d2254a9d0a41a2 (do not edit this line) */
