/* Generated By:JJTree: Do not edit this line. ASTbool.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTbool extends SimpleNode {
  public boolean info = false;

  public ASTbool(int id) {
    super(id);
  }

  public ASTbool(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "bool " + info;
  }

  public String getType() {
    return "bool";
  }

  @Override
  public String accept(ASTNodeVisitor visitor) {
    return visitor.visit(this);
  }

  public void acceptSemanticAnalysis(SemanticAnalyzer semanticAnalyzer) {
    semanticAnalyzer.visit(this);

    if (children != null) {
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode) children[i];
        if (n != null) {
          n.acceptSemanticAnalysis(semanticAnalyzer);
        }
      }
    }
  }
}
/*
 * JavaCC - OriginalChecksum=7064e952aa942fd46131a1edde577da1 (do not edit this
 * line)
 */
