/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTClassDeclaration extends SimpleNode {
  public String id;
  public String ext;

  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(parser p, int id) {
    super(p, id);
  }

  public String toString() {
    return "class " + id + " " + ext != null ? ("extends " + ext) : "";
  }
}
/* JavaCC - OriginalChecksum=18527d10e528b78e818ee6610e15139d (do not edit this line) */
