/* Generated By:JJTree: Do not edit this line. ASTdiv.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdiv extends SimpleNode {

  public ASTdiv(int id) {
    super(id);
  }

  public ASTdiv(jmm p, int id) {
    super(p, id);
  }

  public String getType() {
    return "int";
  }

  void triggerSemanticAnalysis() throws SemanticException
  {
    SimpleNode left = (SimpleNode)children[0];
    SimpleNode right = (SimpleNode)children[1];

    if(!left.getType().equals("int") || !right.getType().equals("int")){
      throw new SemanticException("At least one of operands of / is not an int at line " + line + ", column " + column + ".");
    }
  }

}
/* JavaCC - OriginalChecksum=8e5bf6cb6320f30a44173f2c5c582639 (do not edit this line) */
