/* Generated By:JJTree: Do not edit this line. ASTid.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTid extends SimpleNode {
  public String info;

  public ASTid(int id) {
    super(id);
  }

  public ASTid(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "id " + info;
  }

  public String getType() {
    // Check if it is in the symbol table of simpleNode
    SimpleNode tempParent = (SimpleNode)parent;
    String answer = null;
    while(tempParent != null){
      if (tempParent instanceof ASTClassDeclaration) {
        answer = ((ASTClassDeclaration) tempParent).symtbl.get(info);
      }
      else if (tempParent instanceof ASTMainDeclaration) {
        answer = ((ASTMainDeclaration) tempParent).symtbl.get(info);
      }
      else if (tempParent instanceof ASTMethodDeclaration) {
        answer = ((ASTMethodDeclaration) tempParent).symtbl.get(info);
      }
      if(answer != null) return answer;
      tempParent = (SimpleNode)tempParent.parent;
    }

    return "Error";
  }

}
/* JavaCC - OriginalChecksum=26eb977e90f51861269bce1db317103c (do not edit this line) */
