/* Generated By:JJTree: Do not edit this line. ASTid.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTid extends SimpleNode {
  public String info;

  public ASTid(int id) {
    super(id);
  }

  public ASTid(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "id " + info;
  }

  public String getType() {
    // Check if it is in the symbol table of simpleNode
    STEntry entry = checkSymbolTable(info);

    return (entry == null) ? "Error" : entry.type;
  }

  void triggerSemanticAnalysis() throws SemanticException
  {
      STEntry entry = checkSymbolTable(info);
      
      if(entry == null || (entry.compareTo(new STVar(-1, info, "", line, column)) < 0))
        throw new SemanticException("Variable may not have been initialized: " + info + " at line " + line + ", column " + column + ".");
    }

}
/* JavaCC - OriginalChecksum=26eb977e90f51861269bce1db317103c (do not edit this line) */
