/* Generated By:JJTree: Do not edit this line. ASTlt.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTlt extends SimpleNode {
  public ASTlt(int id) {
    super(id);
  }

  public ASTlt(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d93dfc0190a2180e38dcb1524cfa67e0 (do not edit this line) */
