/* Generated By:JJTree: Do not edit this line. ASTliteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTliteral extends SimpleNode {
  public String info;

  public ASTliteral(int id) {
    super(id);
  }

  public ASTliteral(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "literal " + info;
  }

  public String getType() {
    return "int";
  }
}
/* JavaCC - OriginalChecksum=570004d639550726751648828304833a (do not edit this line) */
