/* Generated By:JJTree: Do not edit this line. ASTmult.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTmult extends SimpleNode {

  public ASTmult(int id) {
    super(id);
  }

  public ASTmult(jmm p, int id) {
    super(p, id);
  }

  public String getType() {
    return "int";
  }

  @Override
  public String accept(ASTNodeVisitor visitor) {
    return visitor.visit(this);
  }
}
/*
 * JavaCC - OriginalChecksum=c8ecbec8e2431c5d327a17275c35d236 (do not edit this
 * line)
 */
