import java.util.HashMap;

/* Generated By:JJTree: Do not edit this line. ASTMainDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMainDeclaration extends SimpleNode {
public  int global_order = 1;
  public HashMap<String, STEntry> symtbl = new HashMap<String, STEntry>();

  public String id;

  public ASTMainDeclaration(int id) {
    super(id);
  }

  public ASTMainDeclaration(jmm p, int id) {
    super(p, id);
  }

  public String toString() {
    return "main args=" + id;
  }

  void triggerSemanticAnalysis() throws SemanticException
  {
    /* Symbol Table insertions */

    if(!addToSymbolTable(id, new STVar(-1, id, "String[]", line, column))){
      throw new SemanticException("Variable already defined: " + id + " at line " + line + ", column " + column + ".");
    }
  }

  String getJasmin() {
    String out = ".method static public main(" + getJasminType("String[]") + ")" + getJasminType("void") + "\n";

    return out;
  }
}
/* JavaCC - OriginalChecksum=3ab5bbea112e01d51552a7af0e602a02 (do not edit this line) */
