/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProgram extends SimpleNode {
  public ASTProgram(int id) {
    super(id);
  }

  public ASTProgram(jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b6b360282715b2c2b97bc6c23085ae3 (do not edit this line) */
