/* Generated By:JJTree: Do not edit this line. ASTreportError.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreportError extends SimpleNode {
  public ASTreportError(int id) {
    super(id);
  }

  public ASTreportError(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cd6cb486bd51c9aa2ff2c3836818c72b (do not edit this line) */
