/* Generated By:JJTree: Do not edit this line. ASTrecoverFromError.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrecoverFromError extends SimpleNode {
  public ASTrecoverFromError(int id) {
    super(id);
  }

  public ASTrecoverFromError(parser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4d98e759f95b077f4740e9a7c7b9da90 (do not edit this line) */
