/* Generated By:JJTree: Do not edit this line. ASTsub.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTsub extends SimpleNode {

  public int line;
  public int column;

  public ASTsub(int id) {
    super(id);
  }

  public ASTsub(jmm p, int id) {
    super(p, id);
  }

  public String getType() {
    return "int";
  }

  void triggerSemanticAnalysis() throws SemanticException
  {
    SimpleNode left = (SimpleNode)children[0];
    SimpleNode right = (SimpleNode)children[1];

    if(!left.getType().equals("int") || !right.getType().equals("int")){
      throw new SemanticException("At least one of operands of - is not an int at line " + line + ", column " + column + ".");
    }
  }
}
/* JavaCC - OriginalChecksum=f38f9886273cf50e18bf3c3d7436b843 (do not edit this line) */
