/* Generated By:JJTree: Do not edit this line. ASTsum.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTsum extends SimpleNode {

  public ASTsum(int id) {
    super(id);
  }

  public ASTsum(jmm p, int id) {
    super(p, id);
  }

  public String getType() {
    return "int";
  }

  @Override
  public String accept(ASTNodeVisitor visitor) {
    return visitor.visit(this);
  }
}
/*
 * JavaCC - OriginalChecksum=fd58adc0663531e5eea42a153c98a773 (do not edit this
 * line)
 */
