/* Generated By:JavaCC: Do not edit this line. jmmTreeConstants.java Version 6.0_1 */
public interface jmmTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTARGS = 5;
  public int JJTARG = 6;
  public int JJTTYPE = 7;
  public int JJTSTATEMENT = 8;
  public int JJTIF = 9;
  public int JJTWHILE = 10;
  public int JJTVOID = 11;
  public int JJTAND = 12;
  public int JJTLT = 13;
  public int JJTSUM = 14;
  public int JJTSUB = 15;
  public int JJTMULT = 16;
  public int JJTDIV = 17;
  public int JJTNOT = 18;
  public int JJTLITERAL = 19;
  public int JJTBOOL = 20;
  public int JJTID = 21;
  public int JJT_THIS = 22;
  public int JJT_NEW = 23;
  public int JJTFIELD = 24;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Args",
    "Arg",
    "Type",
    "Statement",
    "If",
    "While",
    "void",
    "and",
    "lt",
    "sum",
    "sub",
    "mult",
    "div",
    "not",
    "literal",
    "bool",
    "id",
    "_this",
    "_new",
    "field",
  };
}
/* JavaCC - OriginalChecksum=e30f052f2deea00be4bdac16eaf6c33f (do not edit this line) */
