/* Generated By:JavaCC: Do not edit this line. parserTreeConstants.java Version 6.0_1 */
public interface parserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTMAINDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTARGS = 5;
  public int JJTARG = 6;
  public int JJTTYPE = 7;
  public int JJTSTATEMENT = 8;
  public int JJTIF = 9;
  public int JJTWHILE = 10;
  public int JJTRECOVERFROMERROR = 11;
  public int JJTREPORTERROR = 12;
  public int JJTVOID = 13;
  public int JJTAND = 14;
  public int JJTLT = 15;
  public int JJTSUM = 16;
  public int JJTSUB = 17;
  public int JJTMULT = 18;
  public int JJTDIV = 19;
  public int JJTLITERAL = 20;
  public int JJTFIELD = 21;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Args",
    "Arg",
    "Type",
    "Statement",
    "If",
    "While",
    "recoverFromError",
    "reportError",
    "void",
    "and",
    "lt",
    "sum",
    "sub",
    "mult",
    "div",
    "literal",
    "field",
  };
}
/* JavaCC - OriginalChecksum=c415a08fadb2f0223d2d1b1f3ee718ba (do not edit this line) */
